# Generated by Django 3.2.3 on 2022-10-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('edescription', models.TextField(max_length=100)),
                ('edate', models.DateField()),
                ('eavalue', models.CharField(max_length=10)),
                ('eivalue', models.CharField(max_length=10)),
                ('ephoto', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
